[package]
name = "muon-website-server"
version = "1.0.0"
authors = ["Mewlips <mewlips@muon.co>"]
edition = "2018"

[dependencies]
actix-rt = "2.8.0"
actix-web = "4.3.1"
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-utils = "3.0.1"
futures = "0.3.1"
env_logger = "0.10.0"
bytes = "1.4.0"
listenfd = "1.0.1"
serde = { version = "1.0.105", features = ["derive"] }
lettre = "0.10.3"
log = "0.4.17"
actix-web-validator = "5.0.1"
validator = { version = "0.16.0", features = ["derive", "validator_derive"] }
