name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - name: copy username secret
      run: echo ${{ secrets.GMAIL_SMTP_USERNAME }} > backend/gmail-smtp-username.txt
    - name: copy password secret
      run: echo ${{ secrets.GMAIL_SMTP_PASSWORD }} > backend/gmail-smtp-password.txt
    - name: Build
      run: cargo build --release
    - name: Copy backend
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.MUON_WEB_HOST }}
        username: ${{ secrets.MUON_WEB_HOST_USERNAME }}
        key: ${{ secrets.MUON_WEB_KEY }}
        strip_components: 2
        source: "target/release/muon-web-server"
        target: /opt/muon-web
    - name: Zola build
      uses: shalzz/zola-deploy-action@v0.19.2
      env:
        BUILD_DIR: frontend
        BUILD_ONLY: true
    - name: copy frontend
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.MUON_WEB_HOST }}
        username: ${{ secrets.MUON_WEB_HOST_USERNAME }}
        key: ${{ secrets.MUON_WEB_KEY }}
        source: "start-server.sh,stop-server.sh,cert-nginx-renew.sh,frontend/public/*"
        target: /opt/muon-web
    - name: restart server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.MUON_WEB_HOST }}
        username: ${{ secrets.MUON_WEB_HOST_USERNAME }}
        key: ${{ secrets.MUON_WEB_KEY }}
        script: /opt/muon-web/stop-server.sh && /opt/muon-web/start-server.sh

